#!/usr/bin/env python
import sys
from networkpinger.model import configure
configure(sys.argv[1])

from networkpinger import model

for line in sys.stdin:
    addr, name = line.strip().split(None, 1)
    h = model.Host.add(addr, name)
    print h
model.Session.commit()
