#!/usr/bin/env python
import sys
from networkpinger.model import configure
configure(sys.argv[1])

from networkpinger import model

addr = sys.argv[1]
name = sys.argv[2]

h = model.Host.add(addr, name)
model.Session.commit()
print h
