#!/usr/bin/env python
import sys
from networkpinger.model import configure
configure(sys.argv[1])

from networkpinger import model

name = sys.argv[2]
try :
    addr = sys.argv[3]
except IndexError:
    addr = None

h = model.Host.add(name, addr)
h.set_active()
model.Session.commit()
print h
