#!/usr/bin/env python
from networkpinger.model.configure import configure
configure("/home/justin/code/network-pinger/development.ini")

from networkpinger import model

import sys

for line in sys.stdin:
    addr, name = line.strip().split(None, 1)
    h = model.Host.add(addr, name)
    print h
model.Session.commit()
