#!/usr/bin/env python
from networkpinger import client
c = client.Client('localhost:8000')
#model.init_model(model.sa.create_engine("sqlite:///development.db"))
from networkpinger.lib import nmapping

import sys

def monitor_up():
    ips = c.get_up_addrs()
    if not ips:
        return
    up, down = nmapping.pingmanyupdown(ips,use_sudo=True)
    if len(down):
        print 'upmon up:%d down:%d' % (len(up), len(down))

    for ip in down:
        c.set_down(ip)

def monitor_down():
    ips = c.get_down_addrs()
    if not ips:
        return
    up, down = nmapping.pingmanyupdown(ips,use_sudo=True)
    if len(up):
        print 'downmon up:%d down:%d' % (len(up), len(down))
    for ip in up:
        c.set_up(ip)

import sys, time
while 1:
    if sys.argv[1]=='up':
        monitor_up()
        time.sleep(10)
    elif sys.argv[1]=='down':
        monitor_down()
        time.sleep(2)
    else:
        break
    sys.stdout.flush()
