#!/usr/bin/env python
from networkpinger.model.configure import configure
configure("/home/justin/code/network-pinger/development.ini")

from networkpinger import model

import sys

addr = sys.argv[1]
name = sys.argv[2]

h = model.Host.add(addr, name)
h.add_alert()
model.Session.commit()
