#!/usr/bin/env python
import sys
from networkpinger.model import configure
configure(sys.argv[1])

from networkpinger import model

import sys

addr = sys.argv[2]
name = sys.argv[3]

h = model.Host.add(addr, name)
h.add_alert()
model.Session.commit()
