#!/usr/bin/env python
import sys
from networkpinger.model import configure
configure(sys.argv[1])

from networkpinger import model

def set_hosts(hosts):
    for addr, name in hosts:
        h = model.Host.add(name, addr)
        if hasattr(h, '_added'):
            print "added", h
        elif not h.active:
            h.set_active()
            print "Activated", h
    model.Session.commit()

    wanted = set(name for (addr, name) in hosts)
    for x in model.Host.all():
        if x.name not in wanted:
            print "removed", x
            x.set_inactive("removed")
    model.Session.commit()

def main():
    hosts = []
    for line in sys.stdin:
        addr, name = line.strip().split(None, 1)
        hosts.append((addr, name))
    set_hosts(hosts)

if __name__ == "__main__":
    main()
