#!/usr/bin/env python
from networkpinger.model.configure import configure
configure("/home/justin/code/network-pinger/development.ini")

from networkpinger import model

import sys

addr = sys.argv[1]

a = model.Alert.query_down().filter_by(addr=addr).first()
if a:
    a.up = True
    model.Session.commit()
