#!/usr/bin/env python
import time
import stomp
import sys
import select
import simplejson

def handle(message):
    msg = simplejson.loads(message.body)
    if msg['up']:
        a = msg['up']
        print 'Up: ',
    if msg['down']:
        print 'Down: ',
        a = msg['down']
    print "%(addr)s %(name)s %(time)s %(uptime)s" % a
        

def watch():
    c = stomp.Stomp('localhost', 61613)
    c.connect()

    c.subscribe(dict(destination='/topic/alert_msgs'))
    for n in range(1000):
        m = c.receive_frame()
        if m:
            handle(m)

if __name__ == "__main__":
    watch()
