#!/usr/bin/env python
import websocket
import sys
import simplejson

def handle(message):
    msg = simplejson.loads(message.body)
    if msg['up']:
        a = msg['up']
        print 'Up: ',
    if msg['down']:
        print 'Down: ',
        a = msg['down']
    print "%(addr)s %(name)s %(time)s %(uptime)s" % a
        

def watch():
    ws = websocket.create_connection("ws://localhost:8888/websocket")
    while True:
        data = ws.recv()
        print data

if __name__ == "__main__":
    watch()
